title: Beneath Open Skies
email: manuelsourdrille@proton.me
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "/beneathopenskies" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: sourdrillemanuel

plugins:
  - jekyll-feed
